<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$arTemplateParameters = array(
	"TYPE_IMG_THUMB" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage("DB_BASE_TYPE_IMG_THUMB"),
			"TYPE" => "LIST",
			"MULTIPLE" => "N",
			"DEFAULT" => "BX_RESIZE_IMAGE_EXACT",
			"VALUES" => (Array(
					"BX_RESIZE_IMAGE_EXACT" => "BX_RESIZE_IMAGE_EXACT",
					"BX_RESIZE_IMAGE_PROPORTIONAL" => "BX_RESIZE_IMAGE_PROPORTIONAL",
					"BX_RESIZE_IMAGE_PROPORTIONAL_ALT" => "BX_RESIZE_IMAGE_PROPORTIONAL_ALT",
			)
			),
	),
	"DISPLAY_IMG_SECTION_WIDTH" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage('DISPLAY_IMG_SECTION_WIDTH'),
			"TYPE" => "STRING",
			"DEFAULT" => ""
	),
	"DISPLAY_IMG_SECTION_HEIGHT" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage('DISPLAY_IMG_SECTION_HEIGHT'),
			"TYPE" => "STRING",
			"DEFAULT" => ""
	),		
	"TYPE_IMG_THUMB_ELEMENT" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage("DB_BASE_TYPE_IMG_THUMB_ELEMENT"),
			"TYPE" => "LIST",
			"MULTIPLE" => "N",
			"DEFAULT" => "BX_RESIZE_IMAGE_EXACT",
			"VALUES" => (Array(
					"BX_RESIZE_IMAGE_EXACT" => "BX_RESIZE_IMAGE_EXACT",
					"BX_RESIZE_IMAGE_PROPORTIONAL" => "BX_RESIZE_IMAGE_PROPORTIONAL",
					"BX_RESIZE_IMAGE_PROPORTIONAL_ALT" => "BX_RESIZE_IMAGE_PROPORTIONAL_ALT",
			)
			),
	),
	"DISPLAY_IMG_WIDTH" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage('DISPLAY_IMG_WIDTH'),
			"TYPE" => "STRING",
			"DEFAULT" => ""
	),
	"DISPLAY_IMG_HEIGHT" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage('DISPLAY_IMG_HEIGHT'),
			"TYPE" => "STRING",
			"DEFAULT" => ""
	),
	"TYPE_IMG_THUMB_POP_UP" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage("DB_BASE_TYPE_IMG_THUMB_POP_UP"),
			"TYPE" => "LIST",
			"MULTIPLE" => "N",
			"DEFAULT" => "BX_RESIZE_IMAGE_EXACT",
			"VALUES" => (Array(
					"BX_RESIZE_IMAGE_EXACT" => "BX_RESIZE_IMAGE_EXACT",
					"BX_RESIZE_IMAGE_PROPORTIONAL" => "BX_RESIZE_IMAGE_PROPORTIONAL",
					"BX_RESIZE_IMAGE_PROPORTIONAL_ALT" => "BX_RESIZE_IMAGE_PROPORTIONAL_ALT",
			)
			),
	),
	"DISPLAY_IMG_WIDTH_POP_UP" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage('DISPLAY_IMG_WIDTH_POP_UP'),
			"TYPE" => "STRING",
			"DEFAULT" => ""
	),
	"DISPLAY_IMG_HEIGHT_POP_UP" => array(
			"PARENT" => "SECTIONS_SETTINGS",
			"NAME" => GetMessage('DISPLAY_IMG_HEIGHT_POP_UP'),
			"TYPE" => "STRING",
			"DEFAULT" => ""
	),
	
	
		

);
?>